# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
pod 'RxSwift', '6.7.1'
pod 'RxCocoa', '6.7.1'

pod 'Realm', '~> 10.54.0'
pod 'RealmSwift', '~> 10.54.0'

end
